import { createFileRoute } from '@tanstack/react-router'
import { useState } from 'react'
[build]
  base = "fullproject"
  command = "npm run build"
  publish = "fullproject/dist"

[functions]
  directory = "fullproject/n
